### ISSUE TITLE
Proposition: use bytes as public and private key types in all programming languages

### ISSUE THREAD

**Issue by Tolsi** [wavesplatform/unified-declarations#2]
Using the keys as the strings limit the format of the keys only in legacy Base58, I think that there should be no such restriction.

**Comment by ebceu4** [comment]
So we're discussing this with Daniil yesterday and realised that libs will mostly be used on the client side, it's convenient to leave only one type for keys. So we decided that strings will do well, but your point is strong. We will discuss it once again.

**Comment by ebceu4** [comment]
Current TS implementation supports both Base58 and Byte outputs
[Check out an example](https://github.com/wavesplatform/waves-crypto/blob/master/test/index.test.ts)
